name: CI/CD for Databricks Notebooks
on:
 push:
   branches:
     - main
jobs:
 # Step 1: Run Databricks Test Notebook
 run-databricks-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Install Databricks CLI
       run: pip install databricks-cli
     # Configure Databricks CLI using AAD by setting environment variables
     - name: Configure Databricks CLI with AAD Environment Variables
       env:
         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
         DATABRICKS_AAD_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
         DATABRICKS_AAD_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
         DATABRICKS_AAD_TENANT_ID: ${{ secrets.TENANT_ID }}
       run: |
         databricks configure --aad-token
     # Run the test notebook on Databricks
     - name: Run Test Notebook on Databricks
       run: |
         databricks runs submit --json '{
           "run_name": "Test Notebook Execution",
           "existing_cluster_id": "1001-143040-dmg5lktw",  # Replace with your cluster ID
           "notebook_task": {
             "notebook_path": "/Workspace/CICD/test_transformations"  # Path to your test notebook
           }
         }'
 # Step 2: Deploy Notebook to Production
 deploy-prod:
   needs: run-databricks-tests
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Install Databricks CLI
       run: pip install databricks-cli
     # Set AAD environment variables for deployment
     - name: Configure Databricks CLI with AAD for Deployment
       env:
         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
         DATABRICKS_AAD_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
         DATABRICKS_AAD_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
         DATABRICKS_AAD_TENANT_ID: ${{ secrets.TENANT_ID }}
       run: |
         databricks configure --aad-token
    # Deploy the notebook to production workspace
     - name: Deploy Notebook to Production
       run: |
         databricks workspace import --overwrite /Workspace/CICD/transformations /Production/Notebooks/transformations
